//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 12:50:38 PM EEST 
//


package com.ilkun.florizm.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ConFlower complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConFlower">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="soil">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="podzolic"/>
 *               &lt;enumeration value="ground"/>
 *               &lt;enumeration value="sod-podzolic"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="visualParameters" type="{http://www.example.com/Flowers}VisPar"/>
 *         &lt;element name="growingTips">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="temperature" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="photophilous">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="yes"/>
 *                         &lt;enumeration value="no"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="watering" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="multiplying" type="{http://www.example.com/Flowers}Mult"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.example.com/Flowers}FlowerName" />
 *       &lt;attribute name="quantity" use="required" type="{http://www.example.com/Flowers}Qnt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConFlower", propOrder = {
    "soil",
    "origin",
    "visualParameters",
    "growingTips",
    "multiplying"
})
public class ConFlower implements Comparable {

    @XmlElement(required = true)
    protected String soil;
    @XmlElement(required = true)
    protected String origin;
    @XmlElement(required = true)
    protected VisPar visualParameters = new VisPar();
    @XmlElement(required = true)
    protected ConFlower.GrowingTips growingTips = new ConFlower.GrowingTips();
    @XmlElement(required = true)
    protected Mult multiplying;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String name;
    @XmlAttribute(name = "quantity", required = true)
    protected int quantity;

    @Override
    public int compareTo(Object o) {
        int res = 0;
        ConFlower fl = (ConFlower)o;
        if (fl.getGrowingTips().getTemperature() >
            this.getGrowingTips().getTemperature()) {
            res = -1;
        }
        else if(fl.getGrowingTips().getTemperature() <
             this.getGrowingTips().getTemperature()) {
            res = 1;
        }
        
        return res;
    }
    
    public String toString() {
        return "\nName: " + name
            + "\nQuantity: " + quantity
            + "\nType of soil: " + soil
            + "\nOrigin: " + origin
            + "\nVisual Parameters:"
            + "\n\tStem: " + visualParameters.getStem().toString()
            + "\n\tLeaf: " + visualParameters.getLeaf().toString()
            + "\n\tSize: " + visualParameters.getSize()
            + "\nGrowning Tips:"
            + "\n\tTemperature: " + growingTips.getTemperature()
            + "\n\tPhotophilous: " + growingTips.photophilous
            + "\n\tWatering: " + growingTips.getWatering()
            + "\n\tMultiplying: " + multiplying
            + "\n";
    }
    
    /**
     * Gets the value of the soil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoil() {
        return soil;
    }

    /**
     * Sets the value of the soil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoil(String value) {
        this.soil = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the visualParameters property.
     * 
     * @return
     *     possible object is
     *     {@link VisPar }
     *     
     */
    public VisPar getVisualParameters() {
        return visualParameters;
    }

    /**
     * Sets the value of the visualParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisPar }
     *     
     */
    public void setVisualParameters(VisPar value) {
        this.visualParameters = value;
    }

    /**
     * Gets the value of the growingTips property.
     * 
     * @return
     *     possible object is
     *     {@link ConFlower.GrowingTips }
     *     
     */
    public ConFlower.GrowingTips getGrowingTips() {
        return growingTips;
    }

    /**
     * Sets the value of the growingTips property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConFlower.GrowingTips }
     *     
     */
    public void setGrowingTips(ConFlower.GrowingTips value) {
        this.growingTips = value;
    }

    /**
     * Gets the value of the multiplying property.
     * 
     * @return
     *     possible object is
     *     {@link Mult }
     *     
     */
    public Mult getMultiplying() {
        return multiplying;
    }

    /**
     * Sets the value of the multiplying property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mult }
     *     
     */
    public void setMultiplying(Mult value) {
        this.multiplying = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
        this.quantity = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="temperature" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="photophilous">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="yes"/>
     *               &lt;enumeration value="no"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="watering" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "temperature",
        "photophilous",
        "watering"
    })
    public static class GrowingTips {

        protected float temperature;
        @XmlElement(required = true)
        protected String photophilous;
        @XmlElement(required = true)
        protected BigInteger watering;

        /**
         * Gets the value of the temperature property.
         * 
         */
        public float getTemperature() {
            return temperature;
        }

        /**
         * Sets the value of the temperature property.
         * 
         */
        public void setTemperature(float value) {
            this.temperature = value;
        }

        /**
         * Gets the value of the photophilous property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhotophilous() {
            return photophilous;
        }

        /**
         * Sets the value of the photophilous property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhotophilous(String value) {
            this.photophilous = value;
        }

        /**
         * Gets the value of the watering property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getWatering() {
            return watering;
        }

        /**
         * Sets the value of the watering property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setWatering(BigInteger value) {
            this.watering = value;
        }

    }

}
