//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 12:50:38 PM EEST 
//


package com.ilkun.florizm.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Mult.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Mult">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="leaf"/>
 *     &lt;enumeration value="stem"/>
 *     &lt;enumeration value="seed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Mult")
@XmlEnum
public enum Mult {

    @XmlEnumValue("leaf")
    LEAF("leaf"),
    @XmlEnumValue("stem")
    STEM("stem"),
    @XmlEnumValue("seed")
    SEED("seed");
    private final String value;

    Mult(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Mult fromValue(String v) {
        for (Mult c: Mult.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
