//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 12:50:38 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/Flowers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ilkun.florizm.entity;
