//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.19 at 12:50:38 PM EEST 
//


package com.ilkun.florizm.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VisPar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisPar">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stem" type="{http://www.example.com/Flowers}FullColor"/>
 *         &lt;element name="leaf" type="{http://www.example.com/Flowers}FullColor"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisPar", propOrder = {
    "stem",
    "leaf",
    "size"
})
public class VisPar {

    @XmlElement(required = true)
    protected FullColor stem;
    @XmlElement(required = true)
    protected FullColor leaf;
    protected float size;

    /**
     * Gets the value of the stem property.
     * 
     * @return
     *     possible object is
     *     {@link FullColor }
     *     
     */
    public FullColor getStem() {
        return stem;
    }

    /**
     * Sets the value of the stem property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullColor }
     *     
     */
    public void setStem(FullColor value) {
        this.stem = value;
    }

    /**
     * Gets the value of the leaf property.
     * 
     * @return
     *     possible object is
     *     {@link FullColor }
     *     
     */
    public FullColor getLeaf() {
        return leaf;
    }

    /**
     * Sets the value of the leaf property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullColor }
     *     
     */
    public void setLeaf(FullColor value) {
        this.leaf = value;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public float getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     */
    public void setSize(float value) {
        this.size = value;
    }

}
